# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

eval $(ssh-agent)

# This configures certain paths specific to your environment, it must be called first.
source $HOME/.dotfiles/config.sh

# These are just the output of `find $HOME/.dotfiles/ -name '*_src.sh'`
source $HOME/.dotfiles/drupal/drush_completion_src.sh
source $HOME/.dotfiles/git/completion_src.sh
source $HOME/.dotfiles/ruby/default_src.sh
source $HOME/.dotfiles/shell/completion/completion_src.sh
source $HOME/.dotfiles/shell/config/default_src.sh
source $HOME/.dotfiles/shell/config/ubuntu_src.sh
source $HOME/.dotfiles/shell/path/default_src.sh
source $HOME/.dotfiles/shell/prompt/default_src.sh
source $HOME/.dotfiles/shell/aliases/common_src.sh
source $HOME/.dotfiles/shell/aliases/default_src.sh
source $HOME/.dotfiles/shell/aliases/special_src.sh
source $HOME/.dotfiles/shell/aliases/utils_src.sh
source $HOME/.dotfiles/shell/bin/default_src.sh
source $HOME/.dotfiles/terminal/colors/default_src.sh
source $HOME/.dotfiles/terminal/colors/arch_src.sh
source $HOME/.dotfiles/terminal/colors/ubuntu_src.sh
source $HOME/.dotfiles/tmux/default_src.sh
source $HOME/.dotfiles/vim/default_src.sh
function blt() {
  if [[ ! -z ${AH_SITE_ENVIRONMENT} ]]; then
    PROJECT_ROOT="/var/www/html/${AH_SITE_GROUP}.${AH_SITE_ENVIRONMENT}"
  elif [ "`git rev-parse --show-cdup 2> /dev/null`" != "" ]; then
    PROJECT_ROOT=$(git rev-parse --show-cdup)
  else
    PROJECT_ROOT="."
  fi

  if [ -f "$PROJECT_ROOT/vendor/bin/blt" ]; then
    $PROJECT_ROOT/vendor/bin/blt "$@"

  # Check for local BLT.
  elif [ -f "./vendor/bin/blt" ]; then
    ./vendor/bin/blt "$@"

  else
    echo "You must run this command from within a BLT-generated project."
    return 1
  fi
}
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/Users/gabriel.sullice/.gem/ruby/2.7.0/bin:$PATH"

# added by travis gem
[ ! -s /Users/gabriel.sullice/.travis/travis.sh ] || source /Users/gabriel.sullice/.travis/travis.sh
